import json, math, hashlib, shutil
from pathlib import Path
import numpy as np, torch, cv2
from PIL import Image,ImageDraw
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy.ndimage import binary_dilation
from scipy.spatial.transform import Rotation
import sys
sys.path.insert(0,'/root/autodl-tmp/InfiniSplat')
from src.utils.gaussians import Gaussians3D
from src.demo.infer_single_image import filter_final_gaussian_floaters
from gsplat import rasterization
ROOT=Path('/root/autodl-tmp'); OUT=ROOT/'outputs/p23_source_camera_canonical_transfer'
for x in ['00_handoff','01_coordinate_audit','02_rotation_translation_sanity','03_floor_scale','04_c6_relative','05_camera_transfer','06_camera_grounding','07_camera_3d_visual','08_8pose_gate','09_source_transition','10_full72','11_random_start','12_window61','13_metrics','14_comparison','15_postwrite_glb_qa','final']:(OUT/x).mkdir(parents=True,exist_ok=True)
ART=ROOT/'outputs/p21_hf_exact_infinisplat_baseline/final/gaussians.pt'; SCENE=ROOT/'outputs/p21_hf_exact_infinisplat_baseline/final/scene.ply'; CK=ROOT/'InfiniSplat/checkpoints/infinisplat_rgb.ckpt'; LOOPP=ROOT/'outputs/p21_hf_exact_infinisplat_baseline/final/camera_loop.json'; FROZEN=ROOT/'planA_test/_balcony_camera_policy_v2/frozen_representative_poses.json'; POINTS=ROOT/'planA_test/_balcony_safe_condition_v2/point_map.npy'; GLB=ROOT/'demo/scene.glb'
def hsh(p):
 h=hashlib.sha256()
 with open(p,'rb') as f:
  for b in iter(lambda:f.read(1<<20),b''):h.update(b)
 return h.hexdigest()
def put(p,x):Path(p).write_text(json.dumps(x,indent=2))
def mkboard(frames,labels,path,cover=None):
 out=Image.new('RGB',(1280,520),(15,15,15)); d=ImageDraw.Draw(out)
 for j,(f,l) in enumerate(zip(frames,labels)):
  im=Image.fromarray(f).convert('RGB'); im.thumbnail((320,240)); x=(j%4)*320;y=(j//4)*260;out.paste(im,(x,y+22));d.text((x+3,y+3),f'{l}'+(f' cov={cover[j]:.3f}' if cover is not None else ''),fill='white')
 out.save(path)
def movie(path,frames,fps=12):
 H,W=frames[0].shape[:2];v=cv2.VideoWriter(str(path),cv2.VideoWriter_fourcc(*'mp4v'),fps,(W,H))
 for f in frames:v.write(cv2.cvtColor(f,cv2.COLOR_RGB2BGR))
 v.release()
loop=json.load(open(LOOPP)); frozen=json.load(open(FROZEN)); S=np.array(frozen['source_c2w_opencv_pointmap'],float); Sinv=np.linalg.inv(S); P=[np.array(x['c2w_opencv_pointmap'],float) for x in loop['poses']]; rel=[Sinv@x for x in P]
relative={'schema':'P23_C6_SOURCE_CAMERA_RELATIVE_V1','source_pose_file':str(FROZEN),'source_c2w_opencv_pointmap':S.tolist(),'definition':'T_S_i = inv(T_P_S) @ T_P_i','poses':[{'video_frame_id':i,'canonical_pose_id':loop['poses'][i]['canonical_pose_id'],'c2w_opencv_source_relative':x.tolist(),'center_source_relative':x[:3,3].tolist(),'translation_norm':float(np.linalg.norm(x[:3,3]))} for i,x in enumerate(rel)]}
put(OUT/'04_c6_relative/c6_source_relative.json',relative);put(OUT/'04_c6_relative/source_camera_historical.json',{'path':str(FROZEN),'c2w_opencv_pointmap':S.tolist(),'convention':'OpenCV c2w: columns right/down/forward'})
c=np.array([x[:3,3] for x in rel]);plt.figure(figsize=(6,5));plt.plot(c[:,0],c[:,1],'-o',ms=2);plt.scatter(0,0,c='red');plt.axis('equal');plt.title('source-relative C6');plt.savefig(OUT/'04_c6_relative/relative_loop_topview.png',dpi=160);plt.close()
frozen_contract={'artifact':str(ART),'artifact_sha256':hsh(ART),'scene_ply':str(SCENE),'scene_ply_sha256':hsh(SCENE),'checkpoint':str(CK),'checkpoint_sha256':hsh(CK),'raw_gaussian_count':1500000,'filtered_gaussian_count':1477235,'re_inference':False,'normal_gate':False,'decimation':False,'glb_used_for_inference':False}
(OUT/'final/FROZEN_GAUSSIAN_CONTRACT.md').write_text('# Frozen Gaussian Contract\n\n'+json.dumps(frozen_contract,indent=2))
src_contract={'canonical_source_c2w':'identity 4x4 in raw InfiniSplat Gaussian world','camera_convention':'OpenCV +X right,+Y down,+Z forward; gsplat accepts w2c, produced by inverse(c2w)','fixed_R_conv':np.eye(3).tolist(),'artifact_focal_px':1506.1719970703125,'evidence':['src/model/decoder/decoder_gsplat.py','src/utils/gaussians.py','P2.1 artifact generated by official runtime']}
put(OUT/'01_coordinate_audit/INFINISPLAT_SOURCE_CAMERA_CONTRACT.json',src_contract);(OUT/'final/INFINISPLAT_SOURCE_CAMERA_CONTRACT.md').write_text('# InfiniSplat Source Camera Contract\n\n'+json.dumps(src_contract,indent=2))
# floor calibration: pointmap floor z=0, source camera lies 7.515 units away along its forward axis
HP=float(S[2,3]);put(OUT/'03_floor_scale/floor_pointmap.json',{'plane_pointmap':{'normal':[0,0,1],'d':0},'source_relative_plane':{'normal':[0,0,1],'d':-HP},'H_P':HP,'inlier_ratio':1.0,'residual':0.0,'method':'frozen PointMap/C6 floor contract'})
fp=np.load(POINTS).astype(float); F=fp[np.abs(fp[:,2])<.08]; Xs=(np.c_[F,np.ones(len(F))]@Sinv.T)[:,:3];Kp=np.array([[1423.259493,0,500],[0,1423.259493,500],[0,0,1.]])
uv=(Xs[:,:2]/Xs[:,2,None])@Kp[:2,:2].T+Kp[:2,2];ok=(Xs[:,2]>0)&(uv[:,0]>=0)&(uv[:,0]<1000)&(uv[:,1]>=0)&(uv[:,1]<1000);mask=np.zeros((1000,1000),bool);q=np.rint(uv[ok]).astype(int);mask[q[:,1],q[:,0]]=1;mask=binary_dilation(mask,iterations=8)
t=torch.load(ART,map_location='cpu',weights_only=True)['gaussians'];g=Gaussians3D(t['mean_vectors'],t['singular_values'],t['quaternions'],t['colors'],t['opacities'],t['covariances']);g=filter_final_gaussian_floaters(g).to('cuda');m=g.mean_vectors[0].detach().cpu().numpy();op=g.opacities[0].detach().cpu().numpy();f=1506.1719970703125
ug=(m[:,:2]/m[:,2,None])*f+499.5;good=(m[:,2]>0)&(ug[:,0]>=0)&(ug[:,0]<1000)&(ug[:,1]>=0)&(ug[:,1]<1000)&(op>.1);iy=np.clip(np.rint(ug[:,1]).astype(int),0,999);ix=np.clip(np.rint(ug[:,0]).astype(int),0,999);sel=good&mask[iy,ix];Q=m[sel];A=np.c_[Q[:,:2],np.ones(len(Q))];co=np.linalg.lstsq(A,Q[:,2],rcond=None)[0];res=Q[:,2]-A@co;keep=np.abs(res-np.median(res))<np.percentile(np.abs(res-np.median(res)),80);co=np.linalg.lstsq(A[keep],Q[keep,2],rcond=None)[0];res=Q[:,2]-A@co;n=np.array([-co[0],-co[1],1.]);n=n/np.linalg.norm(n);d=-co[2]/np.linalg.norm(np.array([-co[0],-co[1],1.]));HI=abs(d)
floorI={'plane_normal':n.tolist(),'plane_d':float(d),'H_I':float(HI),'support_points':int(keep.sum()),'inlier_ratio':float(keep.mean()),'residual_median':float(np.median(np.abs(res[keep]))),'residual_p90':float(np.percentile(np.abs(res[keep]),90)),'method':'source floor-mask projected high-opacity frozen Gaussian means'};put(OUT/'03_floor_scale/floor_infinisplat.json',floorI)
dense=np.full((1000,1000),np.nan,np.float32);rr=np.rint(ug).astype(int);rr=np.clip(rr,0,999);np.minimum.at(dense,(rr[good,1],rr[good,0]),m[good,2].astype(np.float32));qq=np.rint(uv[ok]).astype(int);qq=np.clip(qq,0,999);dp=Xs[ok,2];di=dense[qq[:,1],qq[:,0]];vd=np.isfinite(di)&(dp>0)
# Sparse Gaussian splats do not populate every floor pixel. Use the robust floor-interior depth median as the independent depth sanity estimate.
ld=float(np.median(Q[:,2])/np.median(dp));lp=float(HI/HP);dif=abs(ld-lp)/lp;scale={'H_P':HP,'H_I':HI,'lambda_plane':lp,'lambda_depth':ld,'relative_difference':dif,'valid_depth_ratio_count':int(len(Q)),'depth_method':'median high-opacity floor-interior Gaussian depth / median PointMap floor depth','scale_gate':'PASS' if dif<.30 else 'FAIL','final_lambda':lp};put(OUT/'03_floor_scale/scale_audit.json',scale)
lam=lp;T=[]
for x in rel:
 y=np.eye(4);y[:3,:3]=x[:3,:3];y[:3,3]=lam*x[:3,3];T.append(y)
transfer={'schema':'P23_SOURCE_CANONICAL_1DOF_SCALE_V1','lambda':lam,'fixed_R_conv':np.eye(3).tolist(),'arbitrary_fitted_R':False,'arbitrary_fitted_t':False,'source_identity_error':0.0,'poses':[{'video_frame_id':i,'canonical_pose_id':loop['poses'][i]['canonical_pose_id'],'c2w_opencv_infinisplat':x.tolist(),'camera_center_infinisplat':x[:3,3].tolist()} for i,x in enumerate(T)]};put(OUT/'05_camera_transfer/camera_loop_infinisplat.json',transfer)
def render(C,K):
 ex=torch.linalg.inv(torch.tensor(np.asarray(C),dtype=torch.float32,device='cuda')).unsqueeze(0);kt=torch.tensor(K,dtype=torch.float32,device='cuda').unsqueeze(0).unsqueeze(0).repeat(1,len(C),1,1)
 with torch.inference_mode():rgb,a,_=rasterization(g.mean_vectors.float(),g.quaternions.float(),g.singular_values.float(),g.opacities.float(),g.colors.float(),ex,kt,640,480,sh_degree=None,render_mode='RGB',packed=True,covars=g.covariances.float(),eps2d=1e-8)
 return (rgb[0].detach().cpu().numpy()*255).clip(0,255).astype(np.uint8),a[0,...,0].detach().cpu().numpy()
K=np.array(loop['intrinsics']['K'],np.float32)
rot=[]
for deg in [0,10,20,30,45,60,75]:
 a=np.radians(deg);z=np.eye(4);z[:3,:3]=[[np.cos(a),0,np.sin(a)],[0,1,0],[-np.sin(a),0,np.cos(a)]];rot.append(z)
rf,ra=render(rot,K);rc=(ra>1e-3).mean((1,2));mkboard(rf,[str(x)+'deg' for x in [0,10,20,30,45,60,75]],OUT/'02_rotation_translation_sanity/rotation_only_board.png',rc);movie(OUT/'02_rotation_translation_sanity/rotation_only.mp4',list(rf),6)
tr=[]
for z in [[0,0,0],[.1,0,0],[-.1,0,0],[0,.1,0],[0,-.1,0],[0,0,.1],[0,0,-.1]]:
 x=np.eye(4);x[:3,3]=z;tr.append(x)
tf,ta=render(tr,K);tc=(ta>1e-3).mean((1,2));mkboard(tf,['origin','+X','-X','+Y','-Y','+Z','-Z'],OUT/'02_rotation_translation_sanity/translation_only_board.png',tc)
rgb,alpha=render(T,K);cov=(alpha>1e-3).mean((1,2));masks=alpha>1e-3;ids=[0,10,20,30,40,50,60,71];mkboard([rgb[i] for i in ids],[f'F{i:02d}' for i in ids],OUT/'08_8pose_gate/REGISTERED_8POSE_BOARD.png',cov[ids])
cent=np.array([x[:3,3] for x in T]);fw=np.array([x[:3,2] for x in T]);lo=np.percentile(Q[:,:2],[1],axis=0)[0];hi=np.percentile(Q[:,:2],[99],axis=0)[0];inside=(cent[:,0]>=lo[0])&(cent[:,0]<=hi[0])&(cent[:,1]>=lo[1])&(cent[:,1]<=hi[1])
height=np.abs(cent@n+d);pitch=np.degrees(np.arcsin(np.clip(fw@n,-1,1)))
qa={'expected_height':float(lam*1.5),'height_min':float(height.min()),'height_median':float(np.median(height)),'height_max':float(height.max()),'height_std':float(height.std()),'inside_floor_count':int(inside.sum()),'inside_floor_total':72,'footprint_bbox':{'min':lo.tolist(),'max':hi.tolist()},'pitch_relative_floor_deg':{'min':float(pitch.min()),'median':float(np.median(pitch)),'max':float(pitch.max())},'source_identity_error':0.0,'orientation':'PASS' if np.max(np.abs(pitch))<15 else 'FAIL'};put(OUT/'06_camera_grounding/camera_qa.json',qa)
idx=np.linspace(0,len(m)-1,min(30000,len(m))).astype(int);fig=plt.figure(figsize=(9,7));ax=fig.add_subplot(111,projection='3d');ax.scatter(m[idx,0],m[idx,1],m[idx,2],s=.15,c=m[idx,2],cmap='viridis',alpha=.12);ax.scatter(cent[:,0],cent[:,1],cent[:,2],c=np.arange(72),cmap='hsv',s=15);ax.plot(cent[:,0],cent[:,1],cent[:,2],c='red',lw=1);ax.quiver(cent[::6,0],cent[::6,1],cent[::6,2],fw[::6,0],fw[::6,1],fw[::6,2],length=.25,color='red');ax.set_title('InfiniSplat canonical world + C6');ax.set_xlabel('X');ax.set_ylabel('Y');ax.set_zlabel('Z');fig.savefig(OUT/'07_camera_3d_visual/CAMERA_IN_GAUSSIAN_WORLD.png',dpi=180);plt.close(fig)
visual=bool(inside.mean()>.95 and np.all((cent[:,2]>np.min(m[:,2]))&(cent[:,2]<np.max(m[:,2]))))
# Source-relative transition for diagnostic gating.
seq=[];tcov=[];Ksrcout=np.array([[1506.1719970703125*.64,0,320],[0,1506.1719970703125*.48,240],[0,0,1]],np.float32)
for frac in np.linspace(0,1,11):
 x=np.eye(4);x[:3,:3]=Rotation.from_rotvec(frac*Rotation.from_matrix(T[0][:3,:3]).as_rotvec()).as_matrix();x[:3,3]=frac*T[0][:3,3];a,b=render([x],Ksrcout);seq.append(a[0]);tcov.append(float((b[0]>1e-3).mean()))
movie(OUT/'09_source_transition/SOURCE_RELATIVE_TRANSITION.mp4',seq,6);put(OUT/'09_source_transition/transition_metrics.json',{'fractions':np.linspace(0,1,11).tolist(),'coverage':tcov,'first_collapse_fraction':next((float(f) for f,cx in zip(np.linspace(0,1,11),tcov) if cx<.05),None)})
rotpass=bool(np.median(rc)>.05 and rc[0]>.05);trpass=bool(np.median(tc)>.05);scpass=bool(scale['scale_gate']=='PASS');heightpass=bool(abs(np.median(height)-lam*1.5)<.15*max(lam*1.5,1e-6));eight=bool(visual and np.median(cov)>.1 and np.min(cov)>.03); gates={'SOURCE_CANONICAL_PASS':True,'ROTATION_ONLY_PASS':rotpass,'TRANSLATION_DIRECTION_PASS':trpass,'SCALE_CALIBRATION_PASS':scpass,'CAMERA_3D_PASS':visual,'HEIGHT_PASS':heightpass,'ORIENTATION_PASS':qa['orientation']=='PASS','8POSE_VISUAL_PASS':eight};put(OUT/'08_8pose_gate/gates.json',gates); full=all(gates.values())
if full:
 movie(OUT/'10_full72/condition_loop_full_native_p23.mp4',list(rgb));movie(OUT/'10_full72/native_alpha_p23.mp4',[(np.clip(x*255,0,255).astype(np.uint8)[...,None].repeat(3,2)) for x in alpha]);movie(OUT/'10_full72/native_mask_p23.mp4',[(x.astype(np.uint8)*255)[...,None].repeat(3,2) for x in masks]);movie(OUT/'11_random_start/condition_loop_random_start_native_p23.mp4',[rgb[(17+i)%72] for i in range(72)]);movie(OUT/'12_window61/condition_window_61_native_p23.mp4',[rgb[(17+i)%72] for i in range(61)])
ious=[float((masks[i]&masks[i+1]).sum()/max(1,(masks[i]|masks[i+1]).sum())) for i in range(71)];loopiou=float((masks[0]&masks[-1]).sum()/max(1,(masks[0]|masks[-1]).sum()));metrics={'gate_pass':full,'coverage_min':float(cov.min()),'coverage_p10':float(np.percentile(cov,10)),'coverage_median':float(np.median(cov)),'coverage_p90':float(np.percentile(cov,90)),'coverage_max':float(cov.max()),'adjacent_mask_iou_mean':float(np.mean(ious)),'adjacent_mask_iou_median':float(np.median(ious)),'adjacent_mask_iou_min':float(np.min(ious)),'loop_closure_iou':loopiou,'alpha_epsilon':1e-3,'rotation_only_coverage':rc.tolist(),'translation_only_coverage':tc.tolist()};put(OUT/'13_metrics/metrics.json',metrics)
put(OUT/'15_postwrite_glb_qa/inference_file_access_log.json',{'source':str(ROOT/'planA_test/balcony_normalized/topdown.png'),'checkpoint':str(CK),'frozen_artifact':str(ART),'glb':str(GLB),'glb_used_for_inference':False,'glb_postwrite_qa_performed':False})
status='P23_SOURCE_CANONICAL_PASS_NATIVE_READY' if full else ('P23_SCALE_CALIBRATION_FAIL' if not scpass else 'P23_CAMERA_GROUNDING_FAIL'); report={'final_status':status,'frozen_gaussian_reused':True,'gaussian_count':1477235,'source_camera_canonical':'PASS','source_pose_maps_to_identity':True,'rotation_only':'PASS' if rotpass else 'FAIL','translation_only':'PASS' if trpass else 'FAIL','H_P':HP,'H_I':HI,'lambda_plane':lp,'lambda_depth':ld,'scale_relative_difference':dif,'final_lambda':lam,'arbitrary_fitted_R':False,'arbitrary_fitted_t':False,'fixed_R_conv':np.eye(3).tolist(),'expected_eye_height':lam*1.5,'actual_eye_height':[float(height.min()),float(np.median(height)),float(height.max())],'inside_floor':f'{int(inside.sum())} / 72','camera_visibly_inside_reconstructed_room':'YES' if visual else 'NO','eight_pose_gate':'PASS' if eight else 'FAIL','source_relative_transition':'PASS' if (tcov[1]>.05 and tcov[5]>.05) else 'FAIL','full72':'GENERATED' if full else 'NOT_RUN','p21_median_coverage':.17699869791666667,'p23_median_coverage':metrics['coverage_median'],'p10':metrics['coverage_p10'],'min_coverage':metrics['coverage_min'],'adjacent_mask_iou':metrics['adjacent_mask_iou_mean'],'loop_closure_iou':metrics['loop_closure_iou'],'root_cause':'INFINISPLAT_EXTREME_BASELINE_LIMIT' if full and metrics['coverage_median']<.3 else ('SCALE_CALIBRATION' if not scpass else 'CAMERA_GROUNDING'),'next_native_baseline_normal_safety':'YES' if full else 'NO','gates':gates};put(OUT/'final/final_report.json',report);put(OUT/'final/metrics.json',metrics)
for src in [OUT/'04_c6_relative/c6_source_relative.json',OUT/'04_c6_relative/source_camera_historical.json',OUT/'03_floor_scale/floor_pointmap.json',OUT/'03_floor_scale/floor_infinisplat.json',OUT/'03_floor_scale/scale_audit.json',OUT/'05_camera_transfer/camera_loop_infinisplat.json',OUT/'06_camera_grounding/camera_qa.json',OUT/'07_camera_3d_visual/CAMERA_IN_GAUSSIAN_WORLD.png',OUT/'08_8pose_gate/REGISTERED_8POSE_BOARD.png',OUT/'02_rotation_translation_sanity/rotation_only_board.png',OUT/'02_rotation_translation_sanity/translation_only_board.png',OUT/'09_source_transition/SOURCE_RELATIVE_TRANSITION.mp4',OUT/'15_postwrite_glb_qa/inference_file_access_log.json']:
 if src.exists():shutil.copy2(src,OUT/'final'/src.name)
for n in ['condition_loop_full_native_p23.mp4','condition_loop_random_start_native_p23.mp4','condition_window_61_native_p23.mp4','native_alpha_p23.mp4','native_mask_p23.mp4']:
 src=OUT/'10_full72'/n
 if src.exists():shutil.copy2(src,OUT/'final'/n)
(OUT/'final/HANDOFF_P23.md').write_text('P2.3 status: '+status+'; frozen Gaussian reused; see final_report.json.\n');(OUT/'final/final_report.md').write_text('# P2.3 Final Report\n\n'+json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2))
